### PR TITLE
create user tool

### PR DESCRIPTION
**Pull request by cturbelin**
New tool to create first user (use same env to init config)

### CODE REVIEW

**Comment by phev8** [comment]
Thanks for the tool.
Some questions/ideas:
- I think it could be a good idea to pass a JSON or yaml file path that describes the user's attributes, instead of needing to enter them one by one in the command line. Ok, eventually it could ask for the password..., but then still you could include some more attributes easily, like auth type, language, roles if subscribed to email. What do you think?
- If you don't want to allow this detailed control, then maybe at least we should rename the method to "create-admin-user"?

**Comment by cturbelin** [comment]
Yes definitively ! I was wondering about this. It's a very simple implementation, just to create the very first admin user and then be able to use the admin api ! I find it preferable to add manually an entry in the mongodb (possibly without the full data structure)
I was thinking most of attributes could be then edited via the web client no ? 
Yes, the name can be changed I do it !

**Comment by phev8** [comment]
Yes, I know, we will need some proper workflow for initial setup... How I used to do it:
- through the web-client, signup one user
- then go to the DB and add the "admin" role
Also not ideal, but that helps also to have the proper data structure set up, and I only add the admin role... so not too much work. 

Probably, we would need something, that the very first user would be automatically an admin, or that the user-management checks every startup if there is an admin user, if no it would create one with default settings. Only then people need to be careful to change their initial password.

**Comment by cturbelin** [comment]
I've seen Sajeeth [propose to do it directly in the db](https://github.com/InfectieradarBE/infectieradar-getting-started/blob/main/system-configuration/1-mongodb-config.md) , but with a very simple data structure (I'm not confortable with this approach since you can have side effects).
Yes, if we setup an initial password we can either : random base32/62 string and show it in the logs, or add an mandatory modification at first use..But as it has to be done once, I'd go simple

**Pull request merged**
